branches:
  only:
    - master

language: python
notifications:
  email: false
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
os:
  - linux

# command to install dependencies
install: pip install -r requirements.txt

# command to run tests
script: python3 -m unittest discover
